import "./globals.css";
import { Inter } from "next/font/google";
import { helvetica } from "../../utils/fonts";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import { ShopProvider } from "../../context/ContextData";


export const metadata = {
  title: "Shop Nike",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} font-helvetica text-[#111111] ${inter.variable} `}
      >
        <ShopProvider>
    
                <Header /> {children} <Footer />
           
        </ShopProvider>
      </body>
    </html>
  );
}
