import "./globals.css";
import { helvetica } from "../../utils/fonts";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${helvetica.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
