import "./globals.css";
import { Inter } from "next/font/google";
import { helvetica } from "../../utils/fonts";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import { ShopProvider } from "../../context/ContextData";
import SessionProvider from "./session-provider/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import AuthScreen from "./auth-screens/page";

export const metadata = {
  title: "Shop Nike",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} font-helvetica text-[#111111] ${inter.variable} `}
      >
        <ShopProvider>
          <SessionProvider>
            {!session ? (
              <AuthScreen />
            ) : (
              <>
                <Header /> {children} <Footer />
              </>
            )}
          </SessionProvider>
        </ShopProvider>
      </body>
    </html>
  );
}
