export const shop = [
  {
    img: "/images/women-shoe-3.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike ZoomX Invincible Run",
    gender: "Women's Shoes",
    color: 3,
    price: 18.99,
  },
  {
    img: "/images/men-top-2.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Pro Top",
    gender: "Men's Top",
    color: 2,
    price: 30.0,
  },
  {
    img: "/images/men-top-1.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Dri-FIT Top",
    gender: "Men's Top",
    color: 1,
    price: 25.0,
  },
  {
    img: "/images/women-full-2.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Sportswear Set",
    gender: "Women's Full Outfit",
    color: 2,
    price: 60.0,
  },
  {
    img: "/images/men-shoe-7.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Victory Tour",
    gender: "Men's Shoes",
    color: 7,
    price: 17.5,
  },
  {
    img: "/images/women-top-2.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Women's Tee",
    gender: "Women's Top",
    color: 2,
    price: 27.0,
  },
  {
    img: "/images/men-shoe-5.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Pegasus 38",
    gender: "Men's Shoes",
    color: 5,
    price: 22.0,
  },
  {
    img: "/images/men-top-5.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Training Top",
    gender: "Men's Top",
    color: 5,
    price: 29.0,
  },
  {
    img: "/images/men-top-3.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Running Top",
    gender: "Men's Top",
    color: 3,
    price: 28.0,
  },
  {
    img: "/images/men-shoe-3.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike React Infinity Run Flyknit",
    gender: "Men's Shoes",
    color: 3,
    price: 20.25,
  },
  {
    img: "/images/kid-top-1.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Kids T-Shirt",
    gender: "Kid's Top",
    color: 1,
    price: 15.0,
  },
  {
    img: "/images/men-top-4.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Sportswear Top",
    gender: "Men's Top",
    color: 4,
    price: 32.0,
  },
  {
    img: "/images/women-shoe-6.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike ZoomX Invincible Run",
    gender: "Women's Shoes",
    color: 6,
    price: 18.99,
  },
  {
    img: "/images/kid-top-4.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Kids Polo",
    gender: "Kid's Top",
    color: 4,
    price: 17.0,
  },
  {
    img: "/images/men-shoe-2.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Max 90",
    gender: "Men's Shoes",
    color: 2,
    price: 15.75,
  },
  {
    img: "/images/men-shoe-1.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Force 1 Mid '07",
    gender: "Men's Shoes",
    color: 1,
    price: 10.5,
  },
  {
    img: "/images/kid-top-2.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Kids Hoodie",
    gender: "Kid's Top",
    color: 2,
    price: 20.0,
  },
  {
    img: "/images/women-top-1.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Women's Tank",
    gender: "Women's Top",
    color: 1,
    price: 25.0,
  },
  {
    img: "/images/men-shoe-6.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Terra Kiger 7",
    gender: "Men's Shoes",
    color: 6,
    price: 19.5,
  },
  {
    img: "/images/kid-top-3.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Yellow Bag",
    gender: "Kid's Bag",
    color: 3,
    price: 18.0,
  },
  {
    img: "/images/men-shoe-4.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Victory Tour",
    gender: "Men's Shoes",
    color: 4,
    price: 17.5,
  },
  {
    img: "/images/women-shoe-4.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Structure 24",
    gender: "Women's Shoes",
    color: 4,
    price: 16.5,
  },
  {
    img: "/images/women-full-3.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Running Set",
    gender: "Women's Full Outfit",
    color: 3,
    price: 65.0,
  },
  {
    img: "/images/women-shoe-2.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Zoom Terra Kiger 7",
    gender: "Women's Shoes",
    color: 2,
    price: 19.5,
  },
  {
    img: "/images/women-full-1.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Yoga Set",
    gender: "Women's Full Outfit",
    color: 1,
    price: 55.0,
  },
  {
    img: "/images/women-shoe-5.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Terra Kiger 7",
    gender: "Women's Shoes",
    color: 5,
    price: 19.5,
  },
  {
    img: "/images/women-shoe-1.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Zoom Pegasus 38",
    gender: "Women's Shoes",
    color: 1,
    price: 22.0,
  },
  {
    img: "/images/women-shoe-7.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Structure 24",
    gender: "Women's Shoes",
    color: 7,
    price: 16.5,
  },
];

export const clothingItems = [
  "Shoes",
  "Sports Bras",
  "Tops & T-shirts",
  "Hoodies & Sweatshirts",
  "Jackets",
  "Trousers & Tights",
  "Shorts",
  "Tracksuits",
  "Jumpsuits & Rompers",
  "Skirts & Dresses",
  "Socks",
  "Accessories",
  "& Equipment",
];
