export const shop = [
  {
    id: 1,
    img: "/images/women-shoe-3.png",
    display1: "/images/boy-1.png",
    display2: "/images/boy-2.png",
    display3: "/images/boy-3.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike ZoomX Invincible Run",
    genderWear: "Women's Shoes",
    gender: "Women",
    colorType: 3,
    color: "pale white",
    price: 18.99,
    description:
      "Layer on style with the Air Max 97. The cracked leather and soft suede update the iconic design while the original look (inspired by Japanese bullet trains and water droplets) still takes centre stage. Easy-to-style colours let you hit the streets quickly.",
    best: "Best Selling Products"
  },
  {
    id: 2,
    img: "/images/men-top-2.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Pro Top",
    genderWear: "Men's Top",
    gender: "Men",
    color: 2,
    price: 30.0,
    best: "New Jordan Shoes"
  },
  {
    id: 3,
    img: "/images/men-top-1.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Dri-FIT Top",
    genderWear: "Men's Top",
    gender: "Men",
    color: 1,
    price: 25.0,
    best: "Best Shoes"
  },
  {
    id: 4,
    img: "/images/women-full-2.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Sportswear Set",
    genderWear: "Women's Full Outfit",
    gender: "Women",
    color: 2,
    price: 60.0,
    best: "Best Women's Shoes"
  },
  {
    id: 5,
    img: "/images/men-shoe-7.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Victory Tour",
    genderWear: "Men's Shoes",
    gender: "Men",
    color: 7,
    price: 17.5,
    best: "New Basketball Shoes"
  },
  {
    id: 6,
    img: "/images/women-top-2.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Women's Tee",
    genderWear: "Women's Top",
    gender: "Women",
    kid: "girl",
    color: 2,
    price: 27.0,
    best: "Best Training & Gym"
  },
  {
    id: 7,
    img: "/images/men-shoe-5.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Pegasus 38",
    genderWear: "Men's Shoes",
    gender: "Men",
    color: 5,
    price: 22.0,
    best: "New Football Shoes"
  },
  {
    id: 8,
    img: "/images/men-top-5.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Training Top",
    genderWear: "Men's Top",
    gender: "Men",
    color: 5,
    price: 29.0,
    best: "Best Men's Shoes"
  },
  {
    id: 9,
    img: "/images/men-top-3.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Running Top",
    genderWear: "Men's Top",
    gender: "Men",
    kid: "boy",
    color: 3,
    price: 28.0,
    best: "Best Selling Products"
  },
  {
    id: 10,
    img: "/images/men-shoe-3.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike React Infinity Run Flyknit",
    genderWear: "Men's Shoes",
    gender: "Men",
    kid: "boy",
    color: 3,
    price: 20.25,
    best: "New Jordan Shoes"
  },
  {
    id: 11,
    img: "/images/kid-top-1.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Kids T-Shirt",
    genderWear: "Kid's Top",
    gender: "Kid",
    color: 1,
    price: 15.0,
    best: "Best Shoes"
  },
  {
    id: 12,
    img: "/images/men-top-4.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Sportswear Top",
    genderWear: "Men's Top",
    gender: "Men",
    kid: "boy",
    color: 4,
    price: 32.0,
    best: "Best Women's Shoes"
  },
  {
    id: 13,
    img: "/images/women-shoe-6.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike ZoomX Invincible Run",
    genderWear: "Women's Shoes",
    gender: "Women",
    kid: "girl",
    color: 6,
    price: 18.99,
    best: "New Basketball Shoes"
  },
  {
    id: 14,
    img: "/images/kid-top-4.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Kids Polo",
    genderWear: "Kid's Top",
    gender: "Kid",
    color: 4,
    price: 17.0,
    best: "Best Training & Gym"
  },
  {
    id: 15,
    img: "/images/men-shoe-2.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Max 90",
    genderWear: "Men's Shoes",
    gender: "Men",
    kid: "boy",
    color: 2,
    price: 15.75,
    best: "New Football Shoes"
  },
  {
    id: 16,
    img: "/images/men-shoe-1.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Force 1 Mid '07",
    genderWear: "Men's Shoes",
    gender: "Men",
    color: 1,
    price: 10.5,
    best: "Best Men's Shoes"
  },
  {
    id: 17,
    img: "/images/kid-top-2.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Kids Hoodie",
    genderWear: "Kid's Top",
    gender: "Kid",
    color: 2,
    price: 20.0,
    best: "Best Selling Products"
  },
  {
    id: 18,
    img: "/images/women-top-1.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Women's Tank",
    genderWear: "Women's Top",
    gender: "Women",
    kid: "girl",
    color: 1,
    price: 25.0,
    best: "New Jordan Shoes"
  },
  {
    id: 19,
    img: "/images/men-shoe-6.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Terra Kiger 7",
    genderWear: "Men's Shoes",
    gender: "Men",
    color: 6,
    price: 19.5,
    best: "Best Shoes"
  },
  {
    id: 20,
    img: "/images/kid-top-3.png",
    brand: "Nike",
    material: "New Arrival",
    title: "Nike Yellow Bag",
    genderWear: "Kid's Bag",
    gender: "Kid",
    kid: "girl",
    color: 3,
    price: 18.0,
    best: "Best Women's Shoes"
  },
  {
    id: 21,
    img: "/images/men-shoe-4.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Victory Tour",
    genderWear: "Men's Shoes",
    gender: "Men",
    kid: "boy",
    color: 4,
    price: 17.5,
    best: "New Basketball Shoes"
  },
  {
    id: 22,
    img: "/images/women-shoe-4.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Structure 24",
    genderWear: "Women's Shoes",
    gender: "Women",
    color: 4,
    price: 16.5,
    best: "Best Training & Gym"
  },
  {
    id: 23,
    img: "/images/women-full-3.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Running Set",
    genderWear: "Women's Full Outfit",
    gender: "Women",
    color: 3,
    price: 65.0,
    best: "Best Selling Products"
  },
  {
    id: 24,
    img: "/images/women-shoe-2.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Zoom Terra Kiger 7",
    genderWear: "Women's Shoes",
    gender: "Women",
    color: 2,
    price: 19.5,
    best: "Best Men's Shoes"
  },
  {
    id: 25,
    img: "/images/women-full-1.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Yoga Set",
    genderWear: "Women's Full Outfit",
    gender: "Women",
    color: 1,
    price: 55.0,
    best: "Best Selling Products"
  },
  {
    id: 26,
    img: "/images/women-shoe-5.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Terra Kiger 7",
    genderWear: "Women's Shoes",
    gender: "Women",
    color: 5,
    price: 19.5,
    best: "New Jordan Shoes"
  },
  {
    id: 27,
    img: "/images/women-shoe-1.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Air Zoom Pegasus 38",
    genderWear: "Women's Shoes",
    gender: "Women",
    color: 1,
    price: 22.0,
    best: "Best Shoes"
  },
  {
    id: 28,
    img: "/images/women-shoe-7.png",
    brand: "Nike",
    material: "Just In",
    title: "Nike Air Zoom Structure 24",
    genderWear: "Women's Shoes",
    gender: "Women",
    color: 7,
    price: 16.5,
    best: "Best Women's Shoes"
  },
  {
    id: 29,
    img: "/images/left-one.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Dri-FIT ADV TechKnit Ultra",
    genderWear: "Men's Short-Sleeve Running Top",
    gender: "Men",
    color: 1,
    price: 12.995,
    best: "New Basketball Shoes"
  },
  {
    id: 30,
    img: "/images/left-two.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Dri-FIT Challenger",
    genderWear: "Men's 18cm (approx.) 2-in-1 Versatile Shorts",
    gender: "Men",
    color: 2,
    price: 14.995,
    best: "Best Training & Gym"
  },
  {
    id: 31,
    img: "/images/left-one.png",
    brand: "Nike",
    material: "Exclusive",
    title: "Nike Dri-FIT ADV TechKnit Ultra",
    genderWear: "Nike Dri-FIT ADV TechKnit Ultra",
    gender: "Nike Dri-FIT ADV TechKnit Ultra",
    color: 3,
    price: 12.995,
    best: "Best Men's Shoes"
  }
];


export const clothingItems = [
  "Shoes",
  "Sports Bras",
  "Tops & T-shirts",
  "Hoodies & Sweatshirts",
  "Jackets",
  "Trousers & Tights",
  "Shorts",
  "Tracksuits",
  "Jumpsuits & Rompers",
  "Skirts & Dresses",
  "Socks",
  "Accessories & Equipment",
];

export const ShoeSize = [
  { size: "UK 6 (EU 40)" },
  { size: "UK 7.5" },
  { size: "UK 9" },
  { size: "UK 10.5" },
  { size: "UK 12" },
  { size: "UK 6.5" },
  { size: "UK 8" },
  { size: "UK 9.5" },
  { size: "UK 11" },
  { size: "UK 7" },
  { size: "UK 8.5" },
  { size: "UK 10" },
  { size: "UK 11.5" },
];
