export const stores = [
  {
    name: "Nike NYC - House of Innovation 000",
    address: "650 5th Ave.",
    city: "New York",
    state: "NY",
    zip: "10019",
    country: "US",
    status: "Closed",
    opensAt: "11 am",
    latitude: 40.7601,
    longitude: -73.9754,
  },
  {
    name: "Nike Portland",
    address: "638 SW 5th Ave.",
    city: "Portland",
    state: "OR",
    zip: "97204",
    country: "US",
    status: "Open",
    opensAt: "10 am",
    latitude: 45.5202,
    longitude: -122.6756,
  },
  {
    name: "Nike Chicago",
    address: "669 N Michigan Ave.",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    country: "US",
    status: "Open",
    opensAt: "10 am",
    latitude: 41.8939,
    longitude: -87.6244,
  },
  {
    name: "Nike San Francisco",
    address: "278 Post St.",
    city: "San Francisco",
    state: "CA",
    zip: "94108",
    country: "US",
    status: "Open",
    opensAt: "10 am",
    latitude: 37.788,
    longitude: -122.4058,
  },
  {
    name: "Nike Miami Beach",
    address: "1035 Lincoln Rd.",
    city: "Miami Beach",
    state: "FL",
    zip: "33139",
    country: "US",
    status: "Open",
    opensAt: "11 am",
    latitude: 25.7907,
    longitude: -80.1406,
  },
  {
    name: "Nike Seattle",
    address: "1500 6th Ave.",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    country: "US",
    status: "Open",
    opensAt: "10 am",
    latitude: 47.6114,
    longitude: -122.3345,
  },
  {
    name: "Nike Atlanta",
    address: "3393 Peachtree Rd. NE",
    city: "Atlanta",
    state: "GA",
    zip: "30326",
    country: "US",
    status: "Open",
    opensAt: "10 am",
    latitude: 33.8484,
    longitude: -84.3635,
  },
  {
    name: "Nike Las Vegas",
    address: "3200 Las Vegas Blvd S",
    city: "Las Vegas",
    state: "NV",
    zip: "89109",
    country: "US",
    status: "Open",
    opensAt: "10 am",
    latitude: 36.1279,
    longitude: -115.1712,
  },
];
